forum/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from forum.views import IndexRedirectView


urlpatterns = [
    path(r"", IndexRedirectView.as_view(), name="index"),
    path(r"users/", include("users.urls")),
    path(r"posting/", include("posting.urls")),
    path(r"admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posting/urls.py
from django.urls import path

from posting import views


app_name = "posting"
urlpatterns = [
    path(r"boards/", views.OverboardView.as_view(), name="overboard"),
    path(
        r"observed/", views.ObservedThreadsListView.as_view(), name="observed_threads"
    ),
    path(r"board/create", views.CreateBoardView.as_view(), name="create_board",),
    path(r"board/<pk>/edit", views.UpdateBoardView.as_view(), name="update_board",),
    path(r"board/<pk>/delete", views.DeleteBoardView.as_view(), name="delete_board",),
    path(
        r"board/<str:board_pk>/threads",
        views.BoardThreadsListView.as_view(),
        name="board_threads_list",
    ),
    path(
        r"board/<str:board_pk>/create_thread/",
        views.CreateThreadView.as_view(),
        name="create_thread",
    ),
    path(
        r"board/<str:board_pk>/thread/<int:pk>/",
        views.ThreadDetailView.as_view(),
        name="thread",
    ),
    path(
        r"board/<str:board_pk>/thread/<int:pk>/delete",
        views.DeleteThreadView.as_view(),
        name="delete_thread",
    ),
    path(
        r"board/<str:board_pk>/thread/<int:pk>/update",
        views.UpdateThreadView.as_view(),
        name="update_thread",
    ),
    path(
        r"board/<str:board_pk>/thread/<int:thread_pk>/create_post/",
        views.CreatePostView.as_view(),
        name="create_post",
    ),
    path(
        r"board/<str:board_pk>/thread/<int:thread_pk>/post/<int:pk>/update",
        views.UpdatePostView.as_view(),
        name="update_post",
    ),
    path(
        r"board/<str:board_pk>/thread/<int:thread_pk>/post/<int:pk>/delete",
        views.DeletePostView.as_view(),
        name="delete_post",
    ),
]

users/urls.py
from django.contrib.auth import views as authentication_views
from django.urls import path

from users import views


app_name = "users"
urlpatterns = [
    path(
        "login/",
        authentication_views.LoginView.as_view(template_name="users/login.html",),
        name="login",
    ),
    path("logout/", authentication_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        authentication_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        authentication_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        authentication_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        authentication_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authentication_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authentication_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(r"signup/", views.SignupView.as_view(), name="signup"),
    path(
        r"add_to_observed/", views.AddToObservedView.as_view(), name="add_to_observed"
    ),
    path(
        r"remove_from_observed/",
        views.RemoveFromObservedView.as_view(),
        name="remove_from_observed",
    ),
    path("user/<pk>", views.UserProfileDetailView.as_view(), name="user_profile"),
    path("user/<pk>/edit", views.UserProfileUpdateView.as_view(), name="edit_profile"),
    path("banned/<int:user_pk>", views.UserBannedView.as_view(), name="banned"),
    path("ban/", views.BanListView.as_view(), name="ban_list"),
    path("ban/<pk>/update", views.UpdateBanView.as_view(), name="update_ban"),
    path("ban/<pk>/delete", views.DeleteBanView.as_view(), name="delete_ban"),
    path("ban/create", views.CreateBanView.as_view(), name="create_ban"),
]

posting/models.py
from datetime import timedelta

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone
from django.utils.http import urlencode

from posting.exceptions import CannotCreateException


class Board(models.Model):
    created = models.DateField(auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=500, blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100, primary_key=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("posting:board_threads_list", kwargs={"board_pk": self.pk},)


class Thread(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    closed = models.DateField(null=True, blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100)
    last_post_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    @property
    def starting_post(self):
        return self.post_set.filter(starting_post=True).first()

    @property
    def file(self):
        if self.starting_post:
            return self.starting_post.file

    @property
    def post_count(self):
        return self.post_set.count() - 1

    def update_most_recent_post_creation_date(self):
        try:
            self.last_post_added = (
                self.post_set.all().order_by("-created_on")[0].created_on
            )
            self.save()
        except IndexError:
            return

    def get_absolute_url(self):
        return reverse(
            "posting:thread", kwargs={"board_pk": self.board.pk, "pk": self.pk},
        )


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(default="")
    created_on = models.DateTimeField(auto_now_add=True)
    updated = models.BooleanField(default=False)
    updated_on = models.DateTimeField(auto_now=True)
    hidden = models.BooleanField(null=True, blank=True)
    parent = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
        related_name="children",
    )
    refers_to = models.ForeignKey(
        "self",
        related_name="referrers_set",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    starting_post = models.BooleanField(default=False)
    thread = models.ForeignKey(Thread, on_delete=models.CASCADE)
    file = models.ImageField(blank=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.original_content = self.content

    def check_plural(self, number):
        if number != 1:
            return "s"
        return ""

    def timedelta_to_humanified_string(self, passed_time):
        seconds = passed_time.seconds
        if passed_time <= timedelta(minutes=1):
            return "{} second{}".format(seconds, self.check_plural(seconds))
        elif passed_time <= timedelta(hours=1):
            minutes = seconds // 60
            return "{} minute{}".format(minutes, self.check_plural(minutes))
        elif passed_time <= timedelta(days=1):
            hours = seconds // 3600
            return "{} hour{}".format(hours, self.check_plural(hours))

        days = passed_time.days
        return "{} day{}".format(days, self.check_plural(days))

    @property
    def time_passed_since_creation(self):
        passed_time = timezone.now() - self.created_on
        return self.timedelta_to_humanified_string(passed_time)

    @property
    def time_passed_since_edition(self):
        if self.updated:
            passed_time = timezone.now() - self.updated_on
            return self.timedelta_to_humanified_string(passed_time)

    def get_absolute_url(self):
        return "{}?{}".format(
            reverse(
                "posting:thread",
                kwargs={"board_pk": self.thread.board.pk, "pk": self.thread.pk},
            ),
            urlencode({"post_id": self.pk}),
        )

    def save(self, *args, **kwargs):
        if self.original_content:
            if not self.updated and self.content != self.original_content:
                self.updated = True

        if self.starting_post:
            try:
                self.thread.post_set.exclude(id=self.id).get(starting_post=True)
            except Post.DoesNotExist:
                pass
            else:
                raise CannotCreateException(
                    "Multiple starting posts in thread {}".format(self.thread.id)
                )

        return super().save(*args, **kwargs)


@receiver(post_save, sender=Post)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        instance.thread.update_most_recent_post_creation_date()

posting/forms.py
from django.forms import ModelForm

from posting.models import Post


class PostForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.thread = kwargs.pop("thread", None)
        self.author = kwargs.pop("author", None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = Post
        fields = ["content", "parent", "refers_to", "file"]

    def save(self):
        post = super().save(commit=False)
        post.thread = self.thread
        post.author = self.author
        post.save()
        return post

posting/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.http import (
    HttpResponseNotFound,
    HttpResponseForbidden,
)
from django.shortcuts import redirect
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy, reverse

from forum.views import BaseViewMixin
from posting.forms import PostForm
from posting.models import Board, Thread, Post


class CrudPermissionViewMixin(BaseViewMixin, PermissionRequiredMixin):
    pass


class BannedUserPostMixin(BaseViewMixin):
    def post(self, request, **kwargs):
        if request.user.userprofile.is_banned:
            return redirect(reverse("users:banned", args=[request.user.id]))
        return super().post(request, **kwargs)


class UpdatePermissionViewAuthorMixin(BannedUserPostMixin):
    permission = ""

    def dispatch(self, request, **kwargs):
        obj = self.get_object()
        if obj.author == request.user or request.user.has_perm(self.permission):
            return super().dispatch(request, **kwargs)
        return HttpResponseForbidden()


class ThreadListViewMixin(BaseViewMixin, ListView):
    paginate_by = 10
    ordering = ["-last_post_added"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["board_pk"] = self.kwargs.get("board_pk")
        context[
            "observed_threads"
        ] = self.request.user.userprofile.observed_threads.all()
        return context


class ObservedThreadsListView(ThreadListViewMixin):
    template_name = "posting/overboard.html"

    def get_queryset(self):
        return self.request.user.userprofile.observed_threads.all()


class OverboardView(ThreadListViewMixin):
    model = Thread
    template_name = "posting/overboard.html"


class BoardThreadsListView(ThreadListViewMixin):
    template_name = "posting/board_threads_list.html"

    def get_queryset(self):
        return Thread.objects.filter(board=self.kwargs.get("board_pk")).order_by(
            "-last_post_added"
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["board"] = Board.objects.get(pk=context["board_pk"])
        return context


class CreateBoardView(CrudPermissionViewMixin, CreateView):
    fields = ["name", "description"]
    model = Board
    permission_required = "posting.add_board"

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super().form_valid(form)


class UpdateBoardView(CrudPermissionViewMixin, UpdateView):
    fields = ["name", "description"]
    model = Board
    permission_required = "posting.change_board"


class DeleteBoardView(CrudPermissionViewMixin, DeleteView):
    model = Board
    permission_required = "posting.delete_board"
    success_url = reverse_lazy("posting:overboard")


class CreateThreadView(BannedUserPostMixin, CreateView):
    model = Thread
    fields = ["name"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["post_form"] = PostForm()
        return context

    def form_valid(self, form):
        try:
            board = Board.objects.get(pk=self.kwargs.get("board_pk"))
        except Board.DoesNotExist:
            return HttpResponseNotFound("<h4>Board not found</h4>")
        author = self.request.user
        form.instance.board = board
        form.instance.author = author
        thread = form.save()
        post_form = PostForm(
            self.request.POST, self.request.FILES, thread=thread, author=author,
        )
        post_form.instance.starting_post = True
        post_form.save()
        return redirect(thread)


class ThreadDetailView(BaseViewMixin, DetailView):
    model = Thread

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        posts = Post.objects.filter(thread=self.kwargs.get("pk"))
        context["board_pk"] = self.kwargs.get("board_pk")
        context["posts"] = {}
        try:
            context["starting_post"] = posts.get(
                thread=self.kwargs.get("pk"), starting_post=True
            )
        except Post.DoesNotExist:
            context["starting_post"] = None
        parentless_posts = (
            posts.filter(
                thread=self.kwargs.get("pk"), starting_post=False, parent=None,
            )
            .order_by("created_on")
            .prefetch_related("children")
        )
        for post in parentless_posts:
            context["posts"][post] = [child for child in post.children.all()]
        return context


class UpdateThreadView(UpdatePermissionViewAuthorMixin, UpdateView):
    model = Thread
    fields = ["name"]
    permission = "posting.change_thread"
    template_name = "posting/edit_thread_form.html"

    def get_context_data(self, **kwargs):
        thread = self.get_object()
        context = super().get_context_data(**kwargs)

        context["post_form"] = PostForm(instance=thread.starting_post)
        return context

    def post(self, request, **kwargs):
        thread = self.get_object()
        post_form = PostForm(
            self.request.POST,
            thread=thread,
            author=thread.starting_post.author,
            instance=thread.starting_post,
        )
        post_form.save()
        return super().post(request, **kwargs)


class DeleteThreadView(UpdatePermissionViewAuthorMixin, DeleteView):
    model = Thread
    permission = "posting.delete_thread"
    template_name = "posting/confirm_delete_thread.html"

    def dispatch(self, request, **kwargs):
        self.success_url = reverse_lazy(
            "posting:board_threads_list", kwargs={"board_pk": kwargs.get("board_pk")},
        )
        return super().dispatch(request, **kwargs)


class CreatePostView(BannedUserPostMixin, CreateView):
    model = Post
    fields = ["content", "parent", "refers_to", "file"]

    def form_valid(self, form):
        thread_pk = self.kwargs.get("thread_pk")
        try:
            form.instance.thread = Thread.objects.get(id=thread_pk)
        except Thread.DoesNotExist:
            return HttpResponseNotFound("<h4>Thread not found</h4>")

        form.instance.author = self.request.user

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["refers_to"] = self.request.GET.get("refers_to")
        context["parent"] = self.request.GET.get("parent")
        return context


class UpdatePostView(UpdatePermissionViewAuthorMixin, UpdateView):
    model = Post
    fields = ["content", "file"]
    permission = "posting.change_post"
    template_name = "posting/update_post_form.html"


class DeletePostView(UpdatePermissionViewAuthorMixin, DeleteView):
    model = Post
    permission = "posting.delete_post"
    template_name = "posting/confirm_delete_post.html"

    def dispatch(self, request, **kwargs):
        thread_pk = self.get_object().thread.pk
        self.success_url = reverse_lazy(
            "posting:thread",
            kwargs={"board_pk": kwargs.get("board_pk"), "pk": thread_pk},
        )
        return super().dispatch(request, **kwargs)

posting/templates/posting/_item.html
{% load forum_tags %}

<div class="row">
    <div class="card mb-4 item">
        <div class="card-header">
            <div class="media flex-wrap w-100 align-items-center"> 
                <a href="{% url 'users:user_profile' pk=item.author.userprofile.pk %}">
                    <img src="{{ item.author.userprofile.avatar_url }}" class="d-block rounded-circle thread-avatar" alt="">
                </a>
                <div class="media-body ml-3">
                    {{ item.author.first_name }}
                    <div class="text-muted small">{{ item.time_passed_since_creation }} ago</div>
                </div>
                <div class="text-muted small ml-3">
                    {% if item.updated %}
                        <div>Edited {{ item.time_passed_since_edition }} ago</div>
                        <hr/>
                    {% endif %}
                    {% if item.refers_to %}
                        <div>in response to {{ item.refers_to.author.first_name }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="card-body">
            {% if item.file %}
                <div class="row">
                    <img src="{{ item.file.url }}" class="align-self-start mr-3 img-fluid img-thumbnail">
                </div>
            {% endif %}
            <div class="row">
                <p>{{ item.content|linebreaks }}</p>
            </div>
        </div>
        <div class="card-footer">
            <div class="col">
                <div class="row">
                    <div class="col">
                        <a href="{% url 'posting:create_post' board_pk=board_pk thread_pk=thread.id %}?refers_to={{ item.id }}&parent={% item_or_parent_id item %}">
                            <button class="btn btn-outline-dark" type="submit">Respond</button>
                        </a>
                        {% if perms.posting.change_post or item.author == user %}
                            <a class="float-right" href="{% url 'posting:update_post' board_pk=board_pk thread_pk=thread.id pk=item.pk%}">
                                <button class="btn btn-outline-dark" type="submit"> edit </button>
                            </a>
                        {% endif %}
                        {% if perms.posting.delete_post or item.author == user %}
                            <a class="float-right delete" href="{% url 'posting:delete_post' board_pk=board_pk thread_pk=thread.id pk=item.pk%}">
                                <button class="btn btn-outline-dark" type="submit">
                                    delete
                                </button>
                            </a>
                        {% endif %}
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

posting/templates/posting/_thread.html
<li class="card thread">
    <div class="card-body">
        <h4 class="media-title">{{ object.name }}</h4>
        <div class="row text">
            <div class="col">
                <p>{{ object.starting_post.content|truncatechars:220|linebreaks }}</p>
            </div>
        </div>
        <div class="card-img-top">
          {% if object.file %}
                <img src="{{ object.file.url }}" class="mx-auto d-block align-self-start mr-3 img-fluid img-thumbnail">
            {% endif %}
        </div>
        <div class="row">
            <div class="col">
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <a href="{% url 'posting:thread' pk=object.id board_pk=object.board.pk%}" class="btn read-more btn-primary">
                    Read more...
                </a>
                <div class="post_count">
                    <i class="fas fa-reply-all"></i> {{ object.post_count }}
                </div>
                <div class="author">
                    <i class="fas fa-user"></i> {{ object.author.first_name }}
                </div>
                <div class="float-right favorite-container justify-content-center" data-thread_id="{{ object.id }}"
                     data-add-url="{% url 'users:add_to_observed' %}" data-remove-url="{% url 'users:remove_from_observed' %}">
                    {% csrf_token %}
                    {% if object in observed_threads %}
                        <a href="#" class="favorite" data-method="remove" >
                            <i class="fas fa-eye-slash"></i>
                        </a>
                    {% else %}
                        <a href="#" class="favorite" data-method="add">
                            <i class="fas fa-eye"></i>
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</li>

posting/templates/posting/board_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Create board{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Create board</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.label_tag }}<br>
                {{ form.name|attr:"class:form-control"}}
                {% for error in form.name.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ form.description.label_tag }}<br>
                {{ form.description|attr:"class:form-control"}}
                {% for error in form.description.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                <input type="submit" class="btnSubmit" value="Create board" />
            </div>
        </form>
    </div>
</div>
{% endblock %}

posting/templates/posting/board_threads_list.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
<div class="row">
    <div class="col">
        <h1> {{ board.name }} </h1>
    </div>
</div>
<ul class="list-inline">
    <a href="{% url 'posting:create_thread' board_pk=board_pk %}" >
        <button class="btn btn-outline-dark col-lg-12" type="submit">Create Thread</button>
    </a>
    {% for object in object_list %}
        {% include 'posting/_thread.html' %}
    {% endfor %}
</ul>
<div class="row justify-content-center">
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% else %}
            <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
        {% endif %}
        {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
                <li class="active page-item"><span class="page-link">{{ i }} <span class="page-link sr-only">(current)</span></span></li>
            {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% else %}
            <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
        {% endif %}
    </ul>
</div>
{% endblock %}

posting/templates/posting/confirm_delete_post.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 justify-content-center">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete this post?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
</div>
{% endblock %}

posting/templates/posting/confirm_delete_thread.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 justify-content-center">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete this thread?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
</div>
{% endblock %}

posting/templates/posting/edit_thread_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Create Thread{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Create thread</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.name.label_tag }}<br>
                {{ form.name|attr:"class:form-control" }}
                {% for error in form.name.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                {{ post_form.content.label_tag }}<br>
                {{ post_form.content|attr:"class:form-control"}}
                {% for error in post_form.content.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                <input type="submit" class="btnSubmit" value="Save thread" />
            </div>
        </form>
    </div>
</div>
{% endblock %}

posting/templates/posting/thread_detail.html
{% extends 'base.html' %}

{% block title %}Wpisy{% endblock %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row justify-content-center">
        <div class="col-sm-12 col-lg-8">
            <div class="row">
                <div class="card mb-4">
                    <div class="card-header">
                        <div class="media flex-wrap w-100 align-items-center"> 
                            <a href="{% url 'users:user_profile' pk=object.author.userprofile.pk %}">
                                <img src="{{ object.author.userprofile.avatar_url }}" class="d-block rounded-circle thread-avatar" alt="">
                            </a>
                            <div class="media-body ml-3">
                                {{ object.author.first_name }}
                                <div class="text-muted small">{{ starting_post.time_passed_since_creation }} ago</div>
                            </div>
                            <div class="text-muted small ml-3">
                                {% if starting_post.updated %}
                                    <div>Edited {{ starting_post.time_passed_since_edition }} ago</div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        {% if starting_post.file %}
                            <div class="row">
                                <img src="{{ starting_post.file.url }}" class="align-self-start mr-3 img-fluid img-thumbnail">
                            </div>
                        {% endif %}
                        <div class="row">
                            <p>{{ starting_post.content|linebreaks }}</p>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <a href="{% url 'posting:create_post' board_pk=board_pk thread_pk=thread.id %}" >
                                        <button class="btn btn-outline-dark" type="submit">Respond</button>
                                    </a>
                                    {% if perms.posting.change_thread or object.author == user %}
                                        <a class="float-right" href="{% url 'posting:update_thread' board_pk=board_pk pk=thread.id %}">
                                            <button class="btn btn-outline-dark" type="submit"> edit </button>
                                        </a>
                                    {% endif %}
                                    {% if perms.posting.delete_thread or object.author == user %}
                                        <a class="float-right delete mr-2" href="{% url 'posting:delete_thread' board_pk=board_pk pk=thread.id %}">
                                            <button class="btn btn-outline-dark" type="submit">
                                                delete
                                            </button>
                                        </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <ul class="timeline">
                        {% for parent, children in posts.items %}
                            <li class="list-unstyled">
                                {% include "posting/_item.html" with item=parent %}
                                {% if children %}
                                    {% for child in children %}
                                        <ul class="timeline">
                                            {% include "posting/_item.html" with item=child %}
                                        </ul>
                                    {% endfor %}
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}