forum/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from forum.views import IndexRedirectView


urlpatterns = [
    path(r"", IndexRedirectView.as_view(), name="index"),
    path(r"users/", include("users.urls")),
    path(r"posting/", include("posting.urls")),
    path(r"admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth import views as authentication_views
from django.urls import path

from users import views


app_name = "users"
urlpatterns = [
    path(
        "login/",
        authentication_views.LoginView.as_view(template_name="users/login.html",),
        name="login",
    ),
    path("logout/", authentication_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        authentication_views.PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_change/done/",
        authentication_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    path(
        "password_reset/",
        authentication_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        authentication_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        authentication_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        authentication_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    path(r"signup/", views.SignupView.as_view(), name="signup"),
    path(
        r"add_to_observed/", views.AddToObservedView.as_view(), name="add_to_observed"
    ),
    path(
        r"remove_from_observed/",
        views.RemoveFromObservedView.as_view(),
        name="remove_from_observed",
    ),
    path("user/<pk>", views.UserProfileDetailView.as_view(), name="user_profile"),
    path("user/<pk>/edit", views.UserProfileUpdateView.as_view(), name="edit_profile"),
    path("banned/<int:user_pk>", views.UserBannedView.as_view(), name="banned"),
    path("ban/", views.BanListView.as_view(), name="ban_list"),
    path("ban/<pk>/update", views.UpdateBanView.as_view(), name="update_ban"),
    path("ban/<pk>/delete", views.DeleteBanView.as_view(), name="delete_ban"),
    path("ban/create", views.CreateBanView.as_view(), name="create_ban"),
]

users/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse
from django.utils import timezone

from posting.models import Thread


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    observed_threads = models.ManyToManyField(Thread, blank=True)
    avatar = models.ImageField(blank=True)

    @property
    def is_banned(self):
        active_bans = [ban for ban in self.user.ban_set.all() if ban.is_active]
        if active_bans:
            return True
        return False

    @property
    def avatar_url(self):
        return self.avatar.url if self.avatar else settings.DEFAULT_AVATAR_URL

    def __str__(self):
        return "{} profile".format(self.user)

    def get_absolute_url(self):
        return reverse("users:user_profile", args=[self.pk],)


class Ban(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    reason = models.CharField(max_length=150)
    created = models.DateTimeField(auto_now_add=True)
    duration = models.DurationField()

    @property
    def is_active(self):
        return (self.created + self.duration) > timezone.now()

    @property
    def time_left(self):
        time_left = (self.created + self.duration) - timezone.now()
        hours, remainder = divmod(int(time_left.total_seconds()), 3600)
        minutes, seconds = divmod(remainder, 60)
        return "{} hours {} minutes and {} seconds left".format(hours, minutes, seconds)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from durationwidget.widgets import TimeDurationWidget

from users.models import Ban


class ExtendedUserCreationForm(UserCreationForm):
    first_name = forms.CharField(label="Visible name", required=True, max_length=15)

    class Meta:
        model = User
        fields = ('username', 'first_name')


class CustomBanForm(forms.ModelForm):
    duration = forms.DurationField(
        widget=TimeDurationWidget(show_minutes=False, show_seconds=False)
    )

    class Meta:
        model = Ban
        fields = ["user", "reason", "duration"]

users/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import HttpResponseForbidden, JsonResponse

from forum.views import BaseViewMixin
from posting.models import Thread
from users.forms import CustomBanForm, ExtendedUserCreationForm
from users.models import Ban, UserProfile


class SignupView(CreateView):
    form_class = ExtendedUserCreationForm
    success_url = reverse_lazy("users:login")
    template_name = "users/signup.html"


class AddToObservedView(BaseViewMixin, View):
    def post(self, request):
        thread_id = request.POST.get("id")

        try:
            thread = Thread.objects.get(id=thread_id)
        except Thread.DoesNotExist:
            return JsonResponse({"result": "error", "error": "thread does not exist"})

        request.user.userprofile.observed_threads.add(thread)

        return JsonResponse({"result": "success", "success": "created"})


class RemoveFromObservedView(BaseViewMixin, View):
    def post(self, request):
        thread_id = request.POST.get("id")

        try:
            thread = Thread.objects.get(id=thread_id)
        except Thread.DoesNotExist:
            return JsonResponse({"result": "error", "error": "thread does not exist"})

        request.user.userprofile.observed_threads.remove(thread)
        return JsonResponse({"result": "success", "success": "deleted"})


class UserProfileDetailView(BaseViewMixin, DetailView):
    model = UserProfile


class UserProfileUpdateView(BaseViewMixin, UpdateView):
    model = UserProfile
    fields = ["avatar"]

    def dispatch(self, request, **kwargs):
        obj = self.get_object()
        if obj.user == request.user:
            return super().dispatch(request, **kwargs)
        return HttpResponseForbidden()


class BanListView(BaseViewMixin, PermissionRequiredMixin, ListView):
    model = Ban
    permission_required = "users.view_ban"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object_list = context.get("object_list")
        context["object_list"] = [item for item in object_list if item.is_active]
        return context


class CreateBanView(BaseViewMixin, PermissionRequiredMixin, CreateView):
    model = Ban
    form_class = CustomBanForm
    permission_required = "users.add_ban"
    success_url = reverse_lazy("users:ban_list",)

    def get_initial(self):
        initial = super().get_initial()
        initial = initial.copy()
        initial["user"] = self.request.GET.get("user_pk")
        return initial


class UpdateBanView(BaseViewMixin, PermissionRequiredMixin, UpdateView):
    model = Ban
    form_class = CustomBanForm
    permission_required = "users.change_ban"
    success_url = reverse_lazy("users:ban_list",)


class DeleteBanView(BaseViewMixin, PermissionRequiredMixin, DeleteView):
    model = Ban
    permission_required = "users.delete_ban"
    success_url = reverse_lazy("users:ban_list",)


class UserBannedView(TemplateView):
    template_name = "users/banned.html"

    def get(self, request, **kwargs):
        user_pk = kwargs.get("user_pk")
        if self.request.user.pk != user_pk:
            return HttpResponseForbidden()
        return super().get(request, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user_bans = self.request.user.ban_set.all()
        active_bans = [ban for ban in user_bans if ban.is_active]
        active_bans.sort(key=lambda x: x.created, reverse=True)

        try:
            context["most_recent_ban"] = active_bans[0]
        except IndexError:
            pass

        return context

users/templates/users/ban_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-12 justify-content-center">
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete this ?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>
</div>
{% endblock %}

users/templates/users/ban_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Create post{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Add ban</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.user.label_tag }}<br>
                {{ form.user|attr:"class:form-control"}}
                {% for error in form.user.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                <div class="row">
                    <h4>{{ form.duration.label_tag }}</h4><br>
                    <div clas="col-12">
                        <div class="col-8">
                            {{ form.duration|attr:"class:form-control"}}
                            {% for error in form.duration.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-group">
                {{ form.reason.label_tag }}<br>
                {{ form.reason|attr:"class:form-control"}}
                {% for error in form.reason.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                <input type="submit" class="btnSubmit" value="Add ban" />
            </div>
        </form>
</div>
{% endblock %}

users/templates/users/ban_list.html
{% extends 'base.html' %}

{% block title %}Bans{% endblock %}

{% block content %}
<div class="row my-2">
    <ul class="list-group">
    <h1>Bans</h1>
    {% for object in object_list %}
        <li class="list-group-item">
            {{ object.user.username }} {{ object.time_left }}
            <a href="{% url 'users:update_ban' pk=object.pk %}" >
                <button class="btn btn-outline-dark" type="submit">Edit ban</button>
            </a>
            <a href="{% url 'users:delete_ban' pk=object.pk %}" >
                <button class="btn btn-outline-dark" type="submit">Delete ban</button>
            </a>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

users/templates/users/banned.html
{% extends 'base.html' %}

{% block title %}You are banned{% endblock %}

{% block content %}
<div class="col-lg-12">
    <div class="row my-2">
        {% if most_recent_ban %}
            <h1>You are banned</h1>
            <h1>{{ most_recent_ban.time_left }}</h1>
            <h1>Reason: {{ most_recent_ban.reason }}</h1>
        {% endif %}
    </div>
</div>
{% endblock %}

users/templates/users/login.html
{% extends "base.html" %}

{% block content %}
<div class="container registration-container">
    <div class="row justify-content-center h-100">
        <div class="col-md-12 col-xl-6 login-form-1">
            <h3>Login</h3>
            <form method="post" action="{% url 'users:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" id="username" name="username"  placeholder="Username">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                </div>
                <div class="form-group">
                    <input type="hidden" name="next" value="{% url 'index' %}">
                    <input type="submit" class="btnSubmit" value="Login" />
                </div>
                {% if form.errors %}
                    <div class="form-group">
                        <p class="error">Your username and password didn't match. Please try again.</p>
                    </div>
                {% endif %}
                <div class="form-group">
                    <a href="{% url 'users:signup' %}" class="ForgetPwd">Register</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/signup.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container registration-container">
    <div class="row justify-content-center">
        <div class="col-md-12 col-xl-6 login-form-1">
            <h3>Login</h3>
            <form method="post" action="{% url 'users:signup' %}">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                    {{ field.label_tag }}<br>
                    {{ field|attr:"class:form-control"}}
                    {% for error in field.errors %}
                     <p style="color: red">{{ error }}</p>
                    {% endfor %}
                    </div>
                {% endfor %}
                <div class="form-group">
                    <input type="submit" class="btnSubmit" value="Create account" />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/userprofile_detail.html
{% extends 'base.html' %}

{% block title %}User Profile{% endblock %}

{% block content %}
<div class="col-lg-12">
    <div class="card text-center profile-details">
        <div class="row">
            <div class="col">
                <img class="card-img-top" src="{{ object.avatar_url }}" alt="Card image cap">
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ object.user.first_name}}</h5>
            Joined on: <h4>{{ object.user.date_joined }}</h4>
        </div>
        <div class="card-footer">
            {% if user == object.user %}
                <a href="{% url 'users:edit_profile' pk=object.pk %}">
                    <button class="btn btn-outline-dark" type="submit">Edit profile</button>
                </a>
            {% endif %}
            {% if perms.posting.add_ban %}
                <a href="{% url 'users:create_ban' %}?user_pk={{ user.pk }}" >
                    <button class="btn btn-danger" type="submit">Ban user</button>
                </a>
            {% endif %}
        </div>
    </div>
</h3>
{% endblock %}

users/templates/users/userprofile_form.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}Edit User Profile{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Edit profile</h3>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                {{ form.avatar.label_tag }}<br>
                {{ form.avatar|attr:"class:form-control"}}
                {% for error in form.avatar.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-group">
                <input type="submit" class="btnSubmit" value="edit" />
            </div>
        </form>
    </div>
</div>
{% endblock %}